### ISSUE TITLE
monome-device not accepting grid/led/map commands

### ISSUE THREAD

**Issue by el-quinto** [monome/monome-max-package#6]
monome-device doesn't seem to be accepting /prefix/grid/led/map commands. (nothing displayed on grid). serialosc.maxpat works however.

**Comment by dndrks** [comment]
@el-quinto , apologies for the delay, this didn't trigger a notification email for some reason!

the [2023 grid study files](https://monome.org/docs/grid/studies/max/files/grid-studies-max.zip) which accompany `[monome-device]` use `/prefix/grid/led/map` messages without any trouble -- if you can pass along a patcher where the issue presents itself, i'd be happy to dig in to see where the new object is causing issues!!

**Comment by el-quinto** [comment]
Thanks Dan. I'll try to find the patch I was working on and get back to you, but I just checked and I couldn't find any example usage of /grid/led/map in the grid studies, there is only grid/led/level/map. (please correct me if I'm wrong)

**Comment by el-quinto** [comment]
Here's a quick example patch. If you replace the serialosc object with monome-device the /grid/led/map message no longer functions.

<pre><code>
----------begin_max5_patcher----------
373.3ocqSssZCCCC84Tn+CF+bVy8rz8qLFC2DQmK9Rv1oKix92mujT5VYsck
QvVnKVGcjTNrbQDdibDzXzSnmQQQGrVh71bVhlMDg4jwVFQ6CDyAslrEvwSN
Mvnw6HgKERNjrUQ6RXPWBgwPoGiSNXXfw7QODvCiQuL6SLvoBqWOB4yVoc97
J2r6g5ioomXZeiJ19pBZMgLkk0rJMF0j5typ7h7hUoeK+A38.j4s94xENoUD
eybW.uaqlyotFTTBSpau.aiQXpv3D9yef7UWh7k4dVmW6D0YWi6k2M2u84Nm
ziRse4Uk1Sgs3pP4kOZqq0nhZT15LT4+yZQw06Lg6h5l+5VQHNLiJN6ODOXN
G+neokCp1YdLs1hNAvNPanBhgJEmDTUHneevbyvUb+vMwVRe+dPomdQ.I6Zv
Noxo2DGzohfdUPWA6oyOYxDQYmFF6nXP4KP7X8zHGykcfRLPm64Nt5f1uoIH
10rdRfU9MxkKrA7EPHKChA
-----------end_max5_patcher-----------
</code></pre>

**Comment by dndrks** [comment]
rad, thank you so much, super super helpful for understanding the point-of-departure!
got this fixed up and merged in -- please lmk if you run into any trouble with the latest `monome-device.maxpat`?
thank you!!!!
